//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RealtyWeb.Models
{
    public partial class AppUser
    {
        public AppUser()
        {
            this.Claims = new HashSet<UserClaim>();
            this.Logins = new HashSet<UserLogin>();
            this.PropertyEntry = new HashSet<PropertyEntry>();
            this.UserFavorite = new HashSet<UserFavorite>();
            this.Roles = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string LicenseNo { get; set; }
        public string ProfilePicLink { get; set; }
        public string ProfileDetails { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
    
        public virtual ICollection<UserClaim> Claims { get; set; }
        public virtual ICollection<UserLogin> Logins { get; set; }
        public virtual ICollection<PropertyEntry> PropertyEntry { get; set; }
        public virtual ICollection<UserFavorite> UserFavorite { get; set; }
        public virtual ICollection<UserRole> Roles { get; set; }
    }
    
}
