//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RealtyWeb.Models
{
    public partial class ImageGallery
    {
        public int Id { get; set; }
        public long TranId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual PropertyEntry PropertyEntry { get; set; }
    }
    
}
