//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RealtyWeb.Models
{
    public partial class LocationPath
    {
        public int PathId { get; set; }
        public int BrgyId { get; set; }
        public string BarangayName { get; set; }
        public int CityMunId { get; set; }
        public string City_MunicipalityName { get; set; }
        public int ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
    
}
