//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RealtyWeb.Models
{
    public partial class PropertyIndicator
    {
        public PropertyIndicator()
        {
            this.PropertyEntry = new HashSet<PropertyEntry>();
        }
    
        public int PropIndicatorId { get; set; }
        public string PropIndicatorName { get; set; }
    
        public virtual ICollection<PropertyEntry> PropertyEntry { get; set; }
    }
    
}
