//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RealtyWeb.Models
{
    public partial class PropertyEntry
    {
        public PropertyEntry()
        {
            this.ClientInquiry = new HashSet<ClientInquiry>();
            this.ImageGallery = new HashSet<ImageGallery>();
            this.PointOfInterest = new HashSet<PointOfInterest>();
            this.UserFavorite = new HashSet<UserFavorite>();
        }
    
        public long PropertyEntryId { get; set; }
        public int PropertyId { get; set; }
        public string PropertyTitle { get; set; }
        public string PropertyDetails { get; set; }
        public decimal LotArea { get; set; }
        public decimal FloorArea { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Bedrooms { get; set; }
        public Nullable<int> Baths { get; set; }
        public bool AllowPet { get; set; }
        public bool HasGarden { get; set; }
        public int PropIndicatorId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Status { get; set; }
        public int ContactPerson { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Property Property { get; set; }
        public virtual PropertyIndicator PropertyIndicator { get; set; }
        public virtual ICollection<ClientInquiry> ClientInquiry { get; set; }
        public virtual ICollection<ImageGallery> ImageGallery { get; set; }
        public virtual ICollection<PointOfInterest> PointOfInterest { get; set; }
        public virtual ICollection<UserFavorite> UserFavorite { get; set; }
    }
    
}
