//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RealtyWeb.Models
{
    public partial class Site
    {
        public int Id { get; set; }
        public string AboutUs { get; set; }
        public string ContactUs { get; set; }
        public string CompanyName { get; set; }
        public string Bulletin { get; set; }
        public string Mission { get; set; }
        public string Vision { get; set; }
        public string ImagePath { get; set; }
    }
    
}
