//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RealtyWeb.Models
{
    public partial class UserFavorite
    {
        public int UserFavId { get; set; }
        public int UserId { get; set; }
        public long PropertyEntryId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual PropertyEntry PropertyEntry { get; set; }
    }
    
}
